version: "3.8"

services:
  client:
    container_name: client
    build:
      context: ./client
    volumes:
      - ./client:/client
    ports:
      - 3000:3000
    image: client:react
    command: npm start

  server:
    container_name: server
    build:
      context: ./server
    volumes:
      - ./server:/server
    ports:
      - 5000:5000
    image: server:socket.io
    command: npm start
