apiVersion: v1
kind: Service
metadata:
  name: random-chat-service
spec:
  selector:
    app: random-chat
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000