apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  selector:
    matchLabels:
      app: random-chat-server
      tier: server
      track: stable
  replicas: 3
  template:
    metadata:
      labels:
        app: random-chat-server
        tier: server
        track: stable
    spec:
      containers:
        - name: random-chat-server
          image: "304764655629.dkr.ecr.eu-central-1.amazonaws.com/random-chat-server"
          ports:
            - containerPort: 5000

