apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  selector:
    app: random-chat-server
    tier: server
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 5000
  type: LoadBalancer

